apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zabbix-agent.fullname" . }}
  labels:
    {{- include "zabbix-agent.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "zabbix-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "zabbix-agent.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "zabbix-agent.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- range $key, $env := .Values.env }}
          - name: {{ $key }}
            value: {{ $env | quote }}
          {{- end }}
          ports:
          - containerPort: 10050
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: {{ .Values.scriptVolume.name }}
            mountPath: {{ .Values.scriptVolume.mountPath }}
          - name: user-parameter
            mountPath: /etc/zabbix/zabbix_agentd.d/
      volumes:
        - name: {{ .Values.scriptVolume.name }}
          configMap:
            name: {{ .Values.scriptVolume.configMap.name }}
            items:
	          {{- range $file, $bytes := .Files.Glob "files/*" }}
              - key: {{ base $file }}
                path: {{ base $file }}
            {{- end}}
            defaultMode: {{ .Values.scriptVolume.configMap.defaultMode }} # Permissão de execução dos pelo agent
        - name: user-parameter
          configMap:
            name: {{ .Values.scriptVolume.configMap.name }}
            items:
              - key: user-parameter.conf
                path: user-parameter.conf
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
